# Generated by Django 4.2.1 on 2023-06-07 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_secretinfo_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secretinfo',
            name='msg',
        ),
    ]
