# Generated by Django 4.2.1 on 2023-07-09 18:08

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_secretinfo_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secretinfo',
            name='img',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
