# Generated by Django 4.2.1 on 2023-07-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_securedpasswordstorage_delete_secretinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='securedpasswordstorage',
            name='password',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
